### ISSUE TITLE
Invalid variable reference syntax for variable fetchStreamARN

### ISSUE THREAD

**Issue by Bielik20** [deepakandgupta/serverless-dynamodb-stream-arn-plugin#1]
Hi, when trying to use this plugin I am getting:

```
 Invalid variable reference syntax for variable fetchStreamARN(my-database-name). You can only reference env vars, options, & files. You can check our docs for more info.
```

Is there something I am doing wrong?

**Comment by deepakandgupta** [comment]
Hey @Bielik20,
It seems that you might have not added the plugin in the plugins section of the serverless.yml file

Add this line in the plugins section
`serverless-dynamodb-stream-arn-plugin`

It needs to added like the image below, can you please check if that helps? 

<img width="722" alt="Screenshot 2021-07-29 at 2 58 01 PM" src="https://user-images.githubusercontent.com/27136846/127468016-5ea78903-8706-45ab-b6ea-943be57fe8b7.png">

**Comment by Bielik20** [comment]
Hi, thanks for a fast response. I did some debugging. It turns out, it doesn't work with region being referenced:

❌  Doesn't work
```yml
provider:
  region: ${file(./src/environments/config.${self:custom.stage}.json):region}
```

✅  Works
```yml
provider:
  region: us-east-2
```

Could this somehow be addressed?

**Comment by deepakandgupta** [comment]
Hey @Bielik20, Tried a version similar to the config you shared and it seems to be working, sharing a snap of it below. 
Ideally, since I am using `resolveConfigurationProperty ` in the plugin, the value of the variables are resolved before they are used.

I think I can help more if you can share a simple example where it does not work. If it is possible :) 
<img width="1103" alt="Screenshot 2021-07-29 at 10 01 52 PM" src="https://user-images.githubusercontent.com/27136846/127530346-b594d121-b386-46a3-a1f6-a220f33c8579.png">

**Comment by Bielik20** [comment]
I have a suspicion. I am doing something like that:

```yml
service: my-service-name

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dynamodb-stream-arn-plugin

custom:
  stage: ${opt:customStage, 'test'}
  alias: ${opt:customAlias, 'noop'}
  bundle:
    linting: false
    tsConfig: 'tsconfig.app.json'
  serverless-offline:
    httpPort: 3339
    lambdaPort: 2339
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.stage}-${self:custom.alias}
  region: ${file(./src/environments/config.${self:custom.stage}.json):region}
  endpointType: regional
  lambdaHashingVersion: 20201221 # removes deprecation warning (remove in serverless v3)
  apiGateway:
    shouldStartNameWithService: true # removes deprecation warning (remove in serverless v3)
  environment:
    APP_ENV: ${self:custom.stage}
    IS_PRODUCTION: ${file(./src/environments/config.${self:custom.stage}.json):is_production}

functions:
  foo:
    handler: src/handlers/foo.handler
    events:
      - stream: ${fetchStreamARN(my-database-name)}
```

I checked, the problem is here:
```yml
custom:
  stage: ${opt:customStage, 'test'}
  alias: ${opt:customAlias, 'noop'}
```

I am using above code to create separate environments for each branch, and then I delete it after PR is merged (alias is usually a branch name). With your `variablesResolutionMode` it wouldn't even work. They are deprecating that in version 3. Still this is version `2.52.0` so it still should be supported. I would have to migrate to [using env variables for that](https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS) :/

I will try that in some time (we have a lot of work right now, I will probably need to hard code arn for now). Once I test it I will post here in case someone else stumbled upon this problem.

Thank you again for your responsiveness 🙇
